import { EventEmitter } from 'events'

export const authEvents = new EventEmitter()

export const EVENT_TYPES = {
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  SESSION_VALIDATED: 'SESSION_VALIDATED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  UNAUTHORIZED_ACCESS_ATTEMPT: 'UNAUTHORIZED_ACCESS_ATTEMPT',
  FORBIDDEN_ACCESS_ATTEMPT: 'FORBIDDEN_ACCESS_ATTEMPT',
  FAILED_LOGIN_ATTEMPT: 'FAILED_LOGIN_ATTEMPT',
} as const